pipeline {
    agent any

    tools {
        maven 'maven3'
        jdk 'jdk21'
    }

    environment {
        IMAGE_NAME = "employee-management"
        CONTAINER_NAME = "employee-management-app"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }
       stage('Verify Java') {
            steps {
                 sh '''
                 echo "JAVA_HOME=$JAVA_HOME"
                 which java
                 java -version
                 mvn -version
                 '''
              }
          }
        stage('Build maven') {
            steps {
                dir('employee-management') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('employee-management') {
                    sh 'docker build -t ${IMAGE_NAME}:latest .'
                }
            }
        }

        stage('Stop Existing Container') {
            steps {
                sh '''
                docker stop ${CONTAINER_NAME} || true
                docker rm ${CONTAINER_NAME} || true
                '''
            }
        }

        stage('Run Docker Container') {
            steps {
                sh '''
                docker run -d \
                --name ${CONTAINER_NAME} \
                -p 8082:8080 \
                ${IMAGE_NAME}:latest
                '''
            }
        }
    }

    post {
        success {
            echo 'Application deployed successfully.'
        }

        failure {
            echo 'Pipeline failed.'
        }
    }
}
